# -*- coding: utf-8 -*-
"""알고리즘 스터디_06_17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xhMnC4GBWVBvCFNnwH6A-TJNy6SRsrq6
"""

## 문제 4 : 두 수의 차


def solution(strlist):
    answer = []
    for i in strlist:
        answer.append(len(i))
    return answer

print(solution(['We', 'are', 'the', 'world!']))


def solution(strlist):
    return [len(i) for i in strlist]

print(solution(['We', 'are', 'the', 'world!']))


solution = lambda strlist: [len(i) for i in strlist]

print(solution(['We', 'are', 'the', 'world!']))

## 문제 5 : 배열 원소의 길이


def solution(strlist):
    answer = []
    for i in strlist:
        answer.append(len(i))
    return answer

print(solution(['We', 'are', 'the', 'world!', "I", "Love", "Programmers."]))


def solution(strlist): return [len(i) for i in strlist]

print(solution(['We', 'are', 'the', 'world!', "I", "Love", "Programmers."]))


solution = lambda strlist: [len(i) for i in strlist]

print(solution(['We', 'are', 'the', 'world!', "I", "Love", "Programmers."]))

## 문제 6 : 제곱수 판별하기

def solution(message):
    answer = []
    for i in message:
        answer.append(len(i) * 2)
    return answer

print(solution("happy birthday!"))
print(solution("I love you~"))


def solution(message): return len(message) * 2

print(solution("happy birthday!"))
print(solution("I love you~"))


solution = lambda strlist: len(strlist) * 2

print(solution("happy birthday!"))
print(solution("I love you~"))