# -*- coding: utf-8 -*-
"""알고리즘 스터디_16_19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jf5s_AeH1oU0_Z5TcoaEhNvtDVrq-uXf
"""

## 문제 10 문자 반복 출력하기

# 기본 풀이
def solution(my_string, n):
    answer = []
    for i in my_string:
        answer.append(i*n)
    return ''.join(answer)

print(solution("hello", 3))


# 간결화
def solution(my_string, n):
    return ''.join([i*n for i in my_string])

print(solution("hello", 3))


# 람다 활용
solution = lambda my_string, n: ''.join([i*n for i in my_string])

print(solution("hello", 3))

## 문제 11 순서쌍의 개수

# 초기 코딩. 실행은 되지만 시간초과.
# 원인 : 다중 for문으로 예상. 시간 복잡도 해결 방안 모색
def solution(n):
    answer = 0
    for i in range(n+1):
        for j in range(n, -1, -1):
            if i * j == n:
                answer+=1
    return answer

print(solution(20))
print(solution(100))


# 다중 for문 해결했지만 여전히 시간 복잡도 해결 숙제가 남음. 현재 O(n)
def solution(n):
    answer = 0
    for i in range(n+1):
        if n % (i+1) == 0:
            answer += 1
    return answer

print(solution(20))
print(solution(100))


# O(n) --> O(√n) 으로 시간 복잡도 해결
def solution(n):
    answer = 0
    for i in range(1, int(n**0.5)+1):
        if n % i == 0:
            if i == n // i:
                answer += 1
            else:
                answer += 2
    return answer

print(solution(20))
print(solution(100))

## 문제 11 중복된 숫자 개수

# for문 (내가 아직 초보인 이유)
def solution(array, n):
    answer = 0
    for i in array:
        if i == n:
            answer += 1
    return answer

print(solution([1, 1, 2, 3, 4, 5], 1))
print(solution([0, 2, 3, 4], 1))


# 간결화
def solution(array, n):
    return array.count(n)

print(solution([1, 1, 2, 3, 4, 5], 1))
print(solution([0, 2, 3, 4], 1))


# 람다 활용
solution = lambda array, n: array.count(n)

print(solution([1, 1, 2, 3, 4, 5], 1))
print(solution([0, 2, 3, 4], 1))