# -*- coding: utf-8 -*-
"""알고리즘 스터디_06_30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dbdXRnOpyeXrWevn_H1Dm9IUVtjjwRmu
"""

## 문제 31 : A 강조하기

def solution(myString):
    return ''.join([i.upper() if i == "a" or i == "A" else i.lower() for i in myString])

print(solution("abstract algebra"))
print(solution("PrOgRaMmErS"))
print(solution("AAAicecreaM"))


def solution(myString):
    return myString.lower().replace('a', 'A')

print(solution("abstract algebra"))
print(solution("PrOgRaMmErS"))
print(solution("AAAicecreaM"))

## 문제 32 : 암호 해독

def solution(cipher, code):
    answer = ''
    for i in range(len(cipher)):
        if (i + 1) % code == 0:
            answer += cipher[i]
    return answer

print(solution("dfjardstddetckdaccccdegk", 4))
print(solution("pfqallllabwaoclk", 2))


def solution(cipher, code):
    return ''.join([cipher[i] for i in range(len(cipher)) if (i + 1) % code == 0])

print(solution("dfjardstddetckdaccccdegk", 4))
print(solution("pfqallllabwaoclk", 2))


def solution(cipher, code):
    return ''.join(cipher[code-1::code])

print(solution("dfjardstddetckdaccccdegk", 4))
print(solution("pfqallllabwaoclk", 2))


def solution(cipher, code):
    return cipher[code-1::code]

print(solution("dfjardstddetckdaccccdegk", 4))
print(solution("pfqallllabwaoclk", 2))

## 문제 33 : rny_string

def solution(rny_string):
    return rny_string.replace('m', 'rn')

print(solution("masterpiece"))
print(solution("programmers"))
print(solution("jerry"))
print(solution("burn"))

## 번외 문제 3 : K번째수

def solution(array, commands):
    answer = []
    sliced_array = []
    for x in range(len(commands)):
        sliced_array = array[commands[x][0]-1 : commands[x][1]]
        sliced_array.sort()
        answer.append(sliced_array[commands[x][2]-1])
    return answer

print(solution([1, 5, 2, 6, 3, 7, 4], [[2, 5, 3], [4, 4, 1], [1, 7, 3]]))



def solution(array, commands):
    answer = []
    for x in commands:
        i, j, k = x
        sliced = array[i-1:j]
        sliced.sort()
        answer.append(sliced[k-1])
    return answer

print(solution([1, 5, 2, 6, 3, 7, 4], [[2, 5, 3], [4, 4, 1], [1, 7, 3]]))



def solution(array, commands):
    return [sorted(array[i-1:j])[k-1] for i, j, k in commands]

print(solution([1, 5, 2, 6, 3, 7, 4], [[2, 5, 3], [4, 4, 1], [1, 7, 3]]))