# -*- coding: utf-8 -*-
"""알고리즘_스터디_07_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-vh-7FBxRv5oi3hK_057N8u8mghfkAmM
"""

## 문제 37 : 정수 부분

# 기본 풀이
def solution(flo):
    return int(flo)

print(solution(1.42))
print(solution(69.32))

## 문제 38 : 0 떼기

# 기본 for문 풀이
def solution(n_str):
    answer = list(n_str)
    for i in n_str:
        if i == '0':
            del answer[0]
        else:
            break
    return ''.join(answer)

print(solution("0010"))
print(solution("854020"))


# lstrip() 활용. strip() 함수는 공백 뿐 아니라 앞뒤 0 도 삭제시킨다
def solution(n_str):
    return n_str.lstrip("0")

print(solution("0010"))
print(solution("854020"))

## 문제 39 : rny_string

# 기본 간결화 풀이
def solution(rny_string):
    return rny_string.replace('m', 'rn')

print(solution("masterpiece"))
print(solution("programmers"))
print(solution("jerry"))
print(solution("burn"))