# -*- coding: utf-8 -*-
"""알고리즘_스터디_25_07_03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JAOxObvRH0CM1XbP7tFxl3RosMfo-sqW
"""

## 문제 40 : 특별한 이차원 배열 1

# 기본 for문 풀이
def solution(n):
    answer = []
    for i in range(n):
        answer.append([0 for j in range(n)])
        answer[i][i] = 1
    return answer

print(solution(3))
print(solution(6))
print(solution(1))


# numpy 활용식 (코테에선 서드파티 라이브러리는 사용 못하므로 실무에서만 유효)
import numpy as np
def solution(n):
    return np.eye(n, dtype=int).tolist()

print(solution(3))
print(solution(6))
print(solution(1))

## 문제 41 : 가장 큰 수 찾기

# 기본 sorted 활용식
def solution(array):
    sorted_arr = sorted(array)
    answer = [sorted_arr[-1]]
    for i in range(len(array)):
        if array[i] == sorted_arr[-1]:
            answer.append(i)
    return answer

print(solution([1, 8, 3]))
print(solution([9, 10, 11, 8]))


# max 활용한 리스트 컴프리헨션
def solution(array):
    return [max(array), array.index(max(array))]

print(solution([1, 8, 3]))
print(solution([9, 10, 11, 8]))


# max를 한번만 사용한 시간복잡도 최적화 리스트 컴프리헨션
def solution(array):
    max_arr = max(array)
    return [max_arr, array.index(max_arr)]

print(solution([1, 8, 3]))
print(solution([9, 10, 11, 8]))

## 문제 42 : 공백으로 구분하기 2

# 기본 spit() 풀이
def solution(my_string):
    return my_string.split()

print(solution(" i    love  you"))
print(solution("    programmers  "))

## 번외 문제 6 : 문자열 다루기 기본

# 기본 if문 활용식
def solution(s):
    if s.isdigit() and (len(s) == 4 or len(s) == 6):
        answer = True
    else:
        answer = False
    return answer

print(solution("a234"))
print(solution("1234"))


# 간결화
def solution(s):
    return s.isdigit() and len(s) in [4,6]

print(solution("a234"))
print(solution("1234"))