# -*- coding: utf-8 -*-
"""알고리즘 스터디_06_26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S4Ueio3DAtC9w9dfeGbRQ-rZjnyqq_3I
"""

## 문제 25 : 문자열 돌리기

# 기본 입출력 for문
str = input()
for i in str:
    print(i)


# join 활용식
str = input()
print('\n'.join(i for i in str))


print(*input(), sep = '\n')

## 문제 26 : 문자열 정렬하기 (1)

# 기본 for문
def solution(my_string):
    answer = []
    for i in my_string:
        if i.isdigit():
            answer.append(int(i))
    return sorted(answer)

print(solution('hi12392'))
print(solution('p2o4i8gj2'))
print(solution('abcde0'))


# 리스트 컴프리헨션 (이것도 대괄호 지우면 제너레이터가 됨)
def solution(my_string):
    return sorted([int(i) for i in my_string if i.isdigit()])

print(solution('hi12392'))
print(solution('p2o4i8gj2'))
print(solution('abcde0'))


# 람다 표현식
solution = lambda my_string: sorted([int(i) for i in my_string if i.isdigit()])

print(solution('hi12392'))
print(solution('p2o4i8gj2'))
print(solution('abcde0'))

## 문제 27 : 부분 문자열인지 확인하기

# 기본 풀이
def solution(my_string, target):
    answer = 0
    if target not in my_string:
        return 0
    else:
        return 1

print(solution("banana", "ana"))
print(solution("banana", "wxyz"))


# 간결화
def solution(my_string, target):
    return 0 if target not in my_string else 1

print(solution("banana", "ana"))
print(solution("banana", "wxyz"))


# 람다 활용
solution = lambda my_string, target: int(target in my_string)

print(solution("banana", "ana"))
print(solution("banana", "wxyz"))