# -*- coding: utf-8 -*-
"""알고리즘 스터디_06_25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14mZ0-F9uZV9uXmrhYWC3VVn1Juqdh4Fe
"""

## 문제 22 : 카운트 업

# 리스트 컴프리헨션
def solution(start_num, end_num):
    return [i for i in range(start_num, end_num + 1)]

print(solution(3, 10))


# 람다 표현식
solution = lambda start_num, end_num: [i for i in range(start_num, end_num + 1)]

print(solution(3, 10))


# 간결화
def solution(start_num, end_num):
    return list(range(start_num, end_num + 1))

print(solution(3, 10))

## 문제 23 : 옷가게 할인 받기

# 기본 풀이
def solution(price):
    answer = price
    if answer >= 500000:
        answer = answer * 0.8
    elif answer >= 300000:
        answer = answer * 0.9
    elif answer >= 100000:
        answer = answer * 0.95
    return int(answer)

print(solution(150000))
print(solution(330000))
print(solution(580000))
print(solution(50000))


# 간결화(?)
def solution(price):
    discount = (
        0.8 if price >= 500000 else
        0.9 if price >= 300000 else
        0.95 if price >= 100000 else
        1
    )
    return int(price * discount)

print(solution(150000))
print(solution(330000))
print(solution(580000))
print(solution(50000))

## 문제 24 : 부분 문자열

# 기본 풀이
def solution(str1, str2):
    if str1 not in str2:
        return 0
    else:
        return 1

print(solution("abc", "aabcc"))
print(solution("tbt", "tbbttb"))


# 간결화
def solution(str1, str2):
    return 0 if str1 not in str2 else 1

print(solution("abc", "aabcc"))
print(solution("tbt", "tbbttb"))


# 람다 표현식
solution = lambda str1, str2: 1 if (str1 in str2) else 0

print(solution("abc", "aabcc"))
print(solution("tbt", "tbbttb"))

## 번외 문제 1 : [PCCE 기출문제] 10번 / 데이터 분석

# 기본 dict활용 풀이
def solution(data, ext, val_ext, sort_by):
    answer = []
    data_map = {
        "code" : 0,
        "date" : 1,
        "maximum" : 2,
        "remain" : 3
    }
    for i in data:
        if i[data_map[ext]] < val_ext:
            answer.append(i)
    answer.sort(key = lambda x: x[data_map[sort_by]])
    return answer

print(solution([[1, 20300104, 100, 80], [2, 20300804, 847, 37], [3, 20300401, 10, 8]], "date", 20300501, "remain"))


# dict + 리스트 컴프리헨션 풀이
def solution(data, ext, val_ext, sort_by):
    data_map = {
        "code" : 0,
        "date" : 1,
        "maximum" : 2,
        "remain" : 3
    }
    answer = [i for i in data if i[data_map[ext]] < val_ext]
    return sorted(answer, key = lambda x: x[data_map[sort_by]])

print(solution([[1, 20300104, 100, 80], [2, 20300804, 847, 37], [3, 20300401, 10, 8]], "date", 20300501, "remain"))