# -*- coding: utf-8 -*-
"""알고리즘_스터디_2025_07_04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1flEBpvG4rYlSnJGfj45cY6n8Ij4urVsZ
"""

## 문제 44 : 주사위 게임 1

# 기본 if문 풀이
def solution(a, b):
    answer = 0
    if (a % 2 != 0) and (b % 2 != 0):
        return a ** 2 + b ** 2
    elif (a + b) % 2 != 0:
        return (a + b) * 2
    return abs(a - b)

print(solution(3, 5))
print(solution(6, 1))
print(solution(2, 4))

## 문제 45 : 배열의 원소 삭제하기

# remove 활용한 for문 풀이
def solution(arr, delete_list):
    for i in delete_list:
        if i in arr:
            arr.remove(i)
    return arr

print(solution([293, 1000, 395, 678, 94], [94, 777, 104, 1000, 1, 12]))
print(solution([110, 66, 439, 785, 1], [377, 823, 119, 43]))


# 리스트 컴프리헨션
def solution(arr, delete_list):
    return [i for i in arr if i not in delete_list]

print(solution([293, 1000, 395, 678, 94], [94, 777, 104, 1000, 1, 12]))
print(solution([110, 66, 439, 785, 1], [377, 823, 119, 43]))

## 문제 44 : ad 제거하기

# append 활용한 기본 for 문
def solution(strArr):
    answer = []
    for i in strArr:
        if "ad" not in i:
            answer.append(i)
    return answer

print(solution(["and","notad","abcd"]))
print(solution(["there","are","no","a","ds"]))


# 리스트 컴프리헨션
def solution(strArr):
    return [i for i in strArr if "ad" not in i]

print(solution(["and","notad","abcd"]))
print(solution(["there","are","no","a","ds"]))

## 번외 문제 7 : 두 개 뽑아서 더하기

# 이중 for문 활용
def solution(numbers):
    answer = []
    for i in range(len(numbers)):
        for j in range(i + 1, len(numbers)):
            answer.append(numbers[i] + numbers[j])
    return sorted(set(answer))

print(solution([2,1,3,4,1]))
print(solution([5,0,2,7]))


# combinations() 활용
# -> n개씩 원소를 뽑는 모든 조합을 만들어주는 함수
# add() = set() 전용 함수기 때문에 한정적으로 사용이 가능
from itertools import combinations
def solution(numbers):
    answer = set()
    for a, b in combinations(numbers, 2):
        answer.add(a + b)
    return sorted(answer)

print(solution([2,1,3,4,1]))
print(solution([5,0,2,7]))