# -*- coding: utf-8 -*-
"""알고리즘 스터디_06_23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UUulv6TdRTtPSOQccm9FNndSiS72czlr
"""

## 문제 16 : 몫 구하기

# 기본 풀이
def solution(num1, num2):
    return num1 // num2

print(solution(33, 22))

solution = lambda num1, num2: num1 // num2

## 문제 17 : 피자 나눠 먹기 (1)

# 기본 풀이
def solution(n):
    if n % 7 == 0:
        return n//7
    elif n > 7:
        return n//7+1
    else:
        return 1


# 간결화
def solution(n): return (n + 6) // 7 if n > 0 else 0


# 람다 표현식
solution = lambda n: (n + 6) // 7 if n > 0 else 0

## 문제 18 : 개미 군단

# 기본 풀이 (가독성 ㅜ,.ㅜ)
def solution(hp):
    return hp // 5 + hp % 5 // 3 + hp % 5 % 3 // 1 + hp % 5 % 3 % 1


# 람다 표현식
solution = lambda hp: hp // 5 + hp % 5 // 3 + hp % 5 % 3 // 1 + hp % 5 % 3 % 1

print(solution(23))
print(solution(24))
print(solution(999))