# -*- coding: utf-8 -*-
"""공통문제_2025_07_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FOmOz6jL-Dq89f9nL7Ju7jHWYNht6Hfb
"""

## 공통 문제 1 : 이상한 문자 만들기

# 이중 for문 기본 풀이
def solution(s):
    answer = []
    for i in s.split(" "):
        t = []
        for j in range(len(i)):
            if j % 2 == 0:
                t.append(i[j].upper())
            else:
                t.append(i[j].lower())
        answer.append(''.join(t))
    return ' '.join(answer)

print(solution("try hello world"))


# 리스트 컴프리헨션
def solution(s):
    answer = []
    for i in s.split(" "):
        t = [i[j].upper() if j % 2 == 0 else i[j].lower() for j in range(len(i))]
        answer.append(''.join(t))
    return ' '.join(answer)

print(solution("try hello world"))


# 조건 중에 "단어 사이 공백은 그대로 유지한다"가 함정이어서 상당 시간 헤맸음.
# -> s.split() 하면 안되고 "꼭" s.split(" ")로 공백 1char 만큼만 split 해줘야함..
# 단어를 두번 해체해서 upper, lower 작업 해줘야 하는 것도 신선했음.