# -*- coding: utf-8 -*-
"""알고리즘 스터디_07_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19wXm7RPpflKHL6f-CO697l_PUOGAh0fX
"""

## 문제 34 : 특정한 문자를 대문자로 바꾸기

def solution(my_string, alp):
    answer = []
    for i in my_string:
        if i in alp:
            answer.append(i.upper())
        else:
            answer.append(i)
    return ''.join(answer)

print(solution("programmers", "p"))
print(solution("lowercase", "x"))


def solution(my_string, alp):
    return my_string.replace(alp, alp.upper())

print(solution("programmers", "p"))
print(solution("lowercase", "x"))

## 문제 35 : 대문자와 소문자

def solution(my_string):
    answer = ''
    for i in my_string:
        if i in my_string.lower():
            answer += i.upper()
        else:
            answer += i.lower()
    return answer

print(solution("cccCCC"))
print(solution("abCdEfghIJ"))


def solution(my_string):
    return ''.join(i.upper() if i in my_string.lower() else i.lower() for i in my_string)

print(solution("cccCCC"))
print(solution("abCdEfghIJ"))


solution = lambda my_string: ''.join(i.upper() if i in my_string.lower() else i.lower() for i in my_string)

print(solution("cccCCC"))
print(solution("abCdEfghIJ"))

## 문제 36 : 배열의 길이에 따라 다른 연산하기

# 기본 for문. 시간복잡도 O(n)
def solution(arr, n):
    answer = []
    for i in range(len(arr)):
        if (len(arr) % 2 != 0) and (i % 2 == 0):
            answer.append(arr[i] + n)
        elif (len(arr) % 2 == 0) and (i % 2 != 0):
            answer.append(arr[i] + n)
        else:
            answer.append(arr[i])
    return answer

print(solution([49, 12, 100, 276, 33], 27))
print(solution([444, 555, 666, 777], 100))


# 간결화 + 변형 for문. 시간복잡도 O(n/2)
def solution(arr, n):
    if len(arr) % 2:
        for i in range(0, len(arr), 2):
            arr[i] += n
    else:
        for i in range(1, len(arr), 2):
            arr[i] += n
    return arr

print(solution([49, 12, 100, 276, 33], 27))
print(solution([444, 555, 666, 777], 100))

## 번외 문제 4 : [PCCE 기출문제] 9번 / 지폐 접기


## 호기롭게 시도했지만 실패한 BFS 코드
# 원인 분석
    # 1. if문 오사용으로 최소 횟수를 잡지 못함.

from collections import deque
def solution(wallet, bill):
    answer = deque()
    answer.append((bill[0], bill[1], 0))
    while answer:
        w, h, folds = answer.popleft()
        if ((wallet[0] >=  w and wallet[1] >= h) or (wallet[0] >= h and wallet[1] >= w)):
            return folds
        if w > 1:
            answer.append((max(1, w//2), h, folds + 1))
        if h > 1:
            answer.append((w, max(1, h//2), folds + 1))
    return -1

print(solution([30, 15], [26, 17]))
print(solution([50, 50], [100, 241]))
print(solution([50, 50], [40, 60]))
print(solution([50, 50], [50, 50]))



# 기본 While문 풀이
def solution(wallet, bill):
    answer = 0
    wmin, wmax = sorted(wallet)
    bw, bh = bill

    while True:
        bmin, bmax = sorted((bw, bh))
        if bmin <= wmin and bmax <= wmax:
            return answer
        if bw >= bh:
            bw //= 2
        else:
            bh //= 2
        answer += 1

print(solution([30, 15], [26, 17]))
print(solution([50, 50], [100, 241]))
print(solution([50, 50], [40, 60]))
print(solution([50, 50], [50, 50]))