# -*- coding: utf-8 -*-
"""알고리즘 스터디_06_27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d2FaBayDha_flRQ532ai7bGItbLxbAlm
"""

## 문제 28 : 덧셈식 출력하기

a, b = map(int, input().strip().split(' '))
print(f"{a} + {b} = {a + b}")
print('{} + {} = {}'.format(a, b, a + b))

## 문제 29 : 숨어있는 숫자의 덧셈 (1)

def solution(my_string):
    answer = 0
    for i in my_string:
        if i.isdigit():
            answer += int(i)
    return answer

print(solution("aAb1B2cC34oOp"))
print(solution("1a2b3c4d123"))


def solution(my_string):
    return sum([int(i) for i in my_string if i.isdigit()])

print(solution("aAb1B2cC34oOp"))
print(solution("1a2b3c4d123"))


solution = lambda my_string: sum([int(i) for i in my_string if i.isdigit()])

print(solution("aAb1B2cC34oOp"))
print(solution("1a2b3c4d123"))

## 문제 30 : 문자열을 정수로 변환하기

def solution(n_str):
    return int(n_str)

print(solution("10"))
print(solution("8542"))

# 번외 문제 2 : 카드 맞추기

# 기본 pop()을 사용한 풀이
def solution(cards1, cards2, goal):
    answer = []
    for i in range(len(goal)):
        if cards1 and goal[i] == cards1[0]:
            answer.append(cards1.pop(0))
        elif cards2 and goal[i] == cards2[0]:
            answer.append(cards2.pop(0))
    return "Yes" if answer == ["i", "want", "to", "drink", "water"] else "No"


print(solution(["i", "drink", "water"], ["want", "to"], ["i", "want", "to", "drink", "water"]))
print(solution(["i", "drink", "water"], ["want", "to"], ["want", "i", "to", "drink", "water"]))


# deque를 이용한 시간복잡도 우월한 풀이
# deque를 사용한 queue 방식은 포인터 지정 개념이라 FIFO 방식에 유리함
from collections import deque
def solution(cards1, cards2, goal):
    answer = []
    dq_cards1 = deque(cards1)
    dq_cards2 = deque(cards2)
    for i in range(len(goal)):
        if dq_cards1 and goal[i] == dq_cards1[0]:
            answer.append(dq_cards1.popleft())
        elif dq_cards2 and goal[i] == dq_cards2[0]:
            answer.append(dq_cards2.popleft())
        else:
            return "No"
    return "Yes"

print(solution(["i", "drink", "water"], ["want", "to"], ["i", "want", "to", "drink", "water"]))  # 출력 결과: Yes
print(solution(["i", "drink", "water"], ["want", "to"], ["want", "i", "to", "drink", "water"]))  # 출력 결과: No