# -*- coding: utf-8 -*-
"""알고리즘 스터디_06_18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1odgkaEw9S1SYxwMsTd0RQ72T4_e3E4PB
"""

## 문제 7 : 숫자 비교하기

# 기본 if문
def solution(num1, num2):
    if num1 == num2:
        answer = -1
    else:
        answer = 1
    return answer
print(solution(2, 3))
print(solution(11, 11))
print(solution(7, 99))


# 간결화
def solution(num1, num2): return -1 if num1 != num2 else 1
print(solution(2, 3))
print(solution(11, 11))
print(solution(7, 99))


# 람다 활용
solution = lambda num1, num2 : 1 if num1 == num2 else -1
print(solution(2, 3))
print(solution(11, 11))
print(solution(7, 99))


# 간결화 2
def solution(num1, num2): return (num1 == num2)*2-1
print(solution(2, 3))
print(solution(11, 11))
print(solution(7, 99))

## 문제 8 : 배열의 유사도

# for문 활용
def solution(s1, s2):
    answer = 0
    for i in s1:
        for j in s2:
            if i == j:
                answer += 1
    return answer

print(solution(["a", "b", "c"], ["com", "b", "d", "p", "c"]))
print(solution(["n", "omg"], ["m", "dot"]))

# 리스트 컴프리헨션
def solution(s1, s2): return 2 if [i for i in s1 for j in s2 if i == j] else 0

print(solution(["a", "b", "c"], ["com", "b", "d", "p", "c"]))
print(solution(["n", "omg"], ["m", "dot"]))

# set()함수 활용
def solution(s1, s2):
     return len(set(s1) & set(s2))
print(solution(["a", "b", "c"], ["com", "b", "d", "p", "c"]))
print(solution(["n", "omg"], ["m", "dot"]))

# lambda 활용
solution= lambda s1, s2: sum(1 for i in s1 for j in s2 if i == j)
print(solution(["a", "b", "c"], ["com", "b", "d", "p", "c"]))
print(solution(["n", "omg"], ["m", "dot"]))

## 제곱수 판별하기

# if문 정석
def solution(n):
    answer = 0
    if n ** 0.5 == int(n ** 0.5) :
          return 1
    else:
          return 2
print(solution(144))
print(solution(976))

# interger()함수 활용
def solution(n):
    if (n**0.5).is_integer() == 1:
          return 1
    else:
          return 2
print(solution(144))
print(solution(976))

# 간결화
def solution(n): return 1 if n ** 0.5 == int(n ** 0.5) else 2

print(solution(144))
print(solution(976))

# 람다 활용
solution = lambda n: 1 if n ** 0.5 == int(n ** 0.5) else 2
print(solution(144))
print(solution(976))