# -*- coding: utf-8 -*-
"""알고리즘 스터디_06_24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WYNw8wwqPK0MIGxB3By6RRUq-1jH67e2
"""

## 문제 19 : 두 수의 곱 구하기


def solution(num1, num2):
    return num1 * num2


solution = lambda num1, num2: num1 * num2

print(solution(3, 4))

## 문제 20 : 배열 두배 만들기

# 기본 풀이
def solution(numbers):
    answer = []
    for i in numbers:
        answer.append(i * 2)
    return answer


# 리스트 컴프리헨션
def solution(numbers):
    return [i * 2 for i in numbers]


# 람다 표현식
solution = lambda numbers: [i * 2 for i in numbers]

print(solution([1, 2, 3, 4, 5]))

## 문제 21 : 꼬리 문자열

# for문 활용식
def solution(str_list, ex):
    answer = ''
    for i in str_list:
        if ex not in i:
            answer += i
    return answer

print(solution(["abd", "def", "ghi"], "ef"))
print(solution(["abd", "bbc", "cbc"], "c"))


# 리스트 컴프리헨션 (대괄호 지우면 그대로 제너레이터 표현식으로 변환가능)
def solution(str_list, ex):
    return ''.join([i for i in str_list if ex not in i])

print(solution(["abd", "def", "ghi"], "ef"))
print(solution(["abd", "bbc", "cbc"], "c"))


# 람다 표현식
solution = lambda str_list, ex: ''.join(i for i in str_list if ex not in i)

print(solution(["abd", "def", "ghi"], "ef"))
print(solution(["abd", "bbc", "cbc"], "c"))