# -*- coding: utf-8 -*-
"""알고리즘 스터디_06_16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C-kD1GdPj9z_Iaj6plPZtNpWI9fXlnS4
"""

## 문제 1 : 나이 출력

# if문을 활용해서 정수형이 아닐 경우 예외 처리
def solution(age):
    if type(age) == int:
        answer = 2022 - age + 1  # 한국식 나이 계산 방식 반영
        return answer
    else:
        return 'age 변수는 정수만 들어가야 합니다'  # 예외 처리

print(solution(40))
print(solution(23))
print(solution('마흔'))

# 이후 코드 간소화 예시
def solution(age):
    answer = 2022 - age + 1
    return answer

print(solution(40))
print(solution(23))

# lambda 표현식으로 깔끔하게
solution = lambda age: 2022 - age + 1

print(solution(40))
print(solution(23))

## 문제 2 : 모음 제거

# 정규표현식으로 간단하게
import re
def solution(my_string):
    answer = re.sub(r'[aeiou]', '', my_string)
    return answer

print(solution('bus'))
print(solution('nice to meet you'))

# replace 반복문 방식
def solution(my_string):
    vowel = ['a', 'e', 'i', 'o', 'u']
    for i in vowel:
        my_string = my_string.replace(i, '')
    return my_string

print(solution('bus'))
print(solution('nice to meet you'))

# 리스트 컴프리헨션
def solution(my_string):
    return ''.join([i for i in my_string if i not in 'aeiou'])

print(solution('bus'))
print(solution('nice to meet you'))

# lambda와 filter 조합
remove_vowels = lambda s: ''.join(filter(lambda ch: ch.lower() not in 'aeiou', s))

print(remove_vowels('bus'))
print(remove_vowels('nice to meet you'))

## 문제 3 : 삼각형의 완성조건 (1)

# sort 사용해서 깔끔하게 처리
def solution(sides):
    sides.sort()
    if sides[0] + sides[1] > sides[2]:
        return 1
    else:
        return 2

# 간결화
def solution(sides):
    return 1 if sum(sides) - max(sides) > max(sides) else 2

# lambda 표현식
solution = lambda sides: 1 if sum(sides) - max(sides) > max(sides) else 2

print(solution([1, 2, 3]))
print(solution([3, 6, 2]))
print(solution([199, 72, 222]))