# -*- coding: utf-8 -*-
"""알고리즘 스터디_06_20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zEP7PD_j8MG1gjMYQ_wKcFzOYkEFIPR0
"""

## 문제 13 : 나머지 구하기

# 기본 풀이
def solution(num1, num2): return num1 % num2

print(solution(3, 2))
print(solution(10, 5))


# 람다 풀이
solution = lambda num1, num2: num1 % num2

print(solution(3, 2))
print(solution(10, 5))

## 문제 14 : 머쓱이보다 키 큰 사람

# 제너레이터 표현식
def solution(array, height):
    return sum(1 for i in array if i > height)

print(solution([149, 180, 192, 170], 167))
print(solution([180, 120, 140], 190))


# 람다 표현식
solution = lambda array, height: sum(1 for i in array if i > height)

print(solution([149, 180, 192, 170], 167))
print(solution([180, 120, 140], 190))

## 문제 15 : 중앙값 구하기

# numpy median() 함수 활용식
import numpy as np
def solution(array):
    if len(array) % 2 == 1:
        return int(np.median(sorted(array)))

print(solution([1, 2, 7, 10, 11]))
print(solution([9, -1, 0]))


# 한줄 코드 (의미는 크게 없다..)
def solution(array):
        return int(np.median(sorted(array))) if len(array) % 2 == 1 else 1

print(solution([1, 2, 7, 10, 11]))
print(solution([9, -1, 0]))